version: '3'
services:
  redis_db:
    image: redis:7.2.3
    ports:
      - "6379:6379"
  mongo_db:
    image: mongo:7.0
    ports:
      - "27017:27017"
  fastapi:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      # Server
      - "MONGO_URL=mongodb://mongo_db:27017/db"
      - "REDIS_HOST=redis_db"
      - "REDIS_PORT=6379"
      # Security
      - "SECRET_KEY=89F4994C137BA7315508FF36999381F50E2C111BB436EE27EC3847D215CE4A51"
    ports:
      - "8000:8000"
    depends_on:
      - redis_db
      - mongo_db
  wagon_emulator:
    build:
      context: wagon_emulator
      dockerfile: Dockerfile
    environment:
      - "SERVER_URL=http://fastapi:8000/"
    depends_on:
      - fastapi
